In [ ]:
!pip install pprint

In [132]:
#       0  ,  1 , 2  , 3 , 4  , 5  , 6  , 7
lst = [ 12 , 18 , 9 , 11 , 17 , 23 , 4 , 14 ]


lst
text = "/home/code/data/data.txt"
a = text.endswith('txt')
print(a)

True


In [9]:
!pip install Tkinter

ERROR: Could not find a version that satisfies the requirement Tkinter (from versions: none)
ERROR: No matching distribution found for Tkinter


In [18]:
# Example file for working with classes
class myClass():
    def method1(self):
        print("Guru99")

    def method2(self,someString):
        print("Software Testing:" + someString)

    def method3(self,a ,b):
        print(a+b)
    
def main():           
  # exercise the class methods
  c = myClass()
  c.method2(" Testing is fun")
  c.method3(1)
  
if __name__== "__main__":
  main()

Software Testing: Testing is fun
5


In [19]:
import tkinter as tk

class Application(tk.Frame):
    def __init__(self, master=None):
        super().__init__(master)
        self.master = master
        self.pack()
        self.create_widgets()

    def create_widgets(self):
        self.hi_there = tk.Button(self)
        self.hi_there["text"] = "Hello World\n(click me)"
        self.hi_there["command"] = self.say_hi
        self.hi_there.pack(side="top")

        self.quit = tk.Button(self, text="QUIT", fg="red",
                              command=self.master.destroy)
        self.quit.pack(side="bottom")

    def say_hi(self):
        print("hi there, everyone!")

root = tk.Tk()
app = Application(master=root)
app.mainloop()

hi there, everyone!
hi there, everyone!


In [26]:
import numpy as np
import random as rd


0.722059827683755

In [24]:


a = np.arange(1, 1+12,).reshape(3,4)

b = np.arange(1, 1+12, dtype = 'float').reshape(3,4)

print(a)
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
